
#The Bot token
token: NjIwMzc2ODcxOTA0NzM5MzU5.XZddVw.ls3t9cUmnN3IXsoKV46vwI-h8Zs

# The Bot Client ID
client_id: 620376871904739359

# Your ID (Optional, for owner commands)
owner_id: 268351613771448320